[book]
authors = ["The Clash Developers"]
language = "en"
src = "src"
title = "The Clash Book: Tutorial"

[build]
build-dir = "../public/tutorial"

[output.html]
site-url = "/tutorial/"

[preprocessor.clash]
command = "mdbook-clash"
clash-cmd = ["clash"]
ghc-cmd = ["ghc"]
