name: "mdBook Preview"

# Run on pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

# Needed for deploying to GitHub Pages and for posting a PR comment
permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'clash-lang' # don't run from forks
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb # v3.21.8
        with:
          extra-conf: |
            extra-substituters = https://clash-lang.cachix.org
            extra-trusted-public-keys = clash-lang.cachix.org-1:/2N1uka38B/heaOAC+Ztd/EWLmF0RLfizWgC5tamCBg=

      - name: Enable Nix cache
        uses: DeterminateSystems/flakehub-cache-action@3be0931021788e3bb4df65f59a555039c2fa2d46 # v3.21.7

      - name: Build the Clash 1.10 book
        run: |
          nix build .#book-clash-1_10 --print-build-logs --out-link site
          cp -RL site public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # The directory mdbook builds to
          # Deploy to a subdirectory like "pr/123"
          destination_dir: ./pr/${{ github.event.pull_request.number }}

      # Post a comment on the PR with the link to the preview
      - name: Post Preview Link Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # Construct the URL for the preview
          message: |
            Thank you for your PR! A preview of your changes is live at
            **[https://docs.clash-lang.org/pr/${{ github.event.pull_request.number }}/](https://docs.clash-lang.org/pr/${{ github.event.pull_request.number }}/)**
